<h2>Domains</h2>
<p>
  <?
	if (session.credentials.admin) then
		local blocked = "";
		local t = Mailman.listDomains(); 
		for k, v in pairs(t) do
			if (k == session.section) then
				if (v.flags == 1) then blocked = "checked"; end
			end
		end
	    printf("<table class=\"elements\" border='0' cellpadding='5' cellspacing='1'>");
		if ( session.section ~= "" ) then
			local domain = session.section;
			printf("<tr><th>Editing %s:</th></tr>",domain);
			printf("<tr><td>");
			printf([[
			<form action="/domains" method="post" id='edit'>
			<div>
			<div >
				<div class='form_key'>
					Domain name:
				</div>
				<div class='form_value'>
					<input type="text" name="domain" value="%s"/>
				</div>
			</div>
			
			<div>
				<div class='form_key'>
					<em>Optional alt. storage path:</em>
				</div>
				<div class='form_value'>
					<input type="text" name="path"/>
				</div>
			</div>
			
			<div>
				<div class='form_key'>
					Block outgoing mail:
				</div>
				<div class='form_value'>
					<input type="checkbox" name="block" value="1" %s/>
				</div>
			</div>
			
	
			<div class='form_el' id='domainsave' >
				<div class='form_key'>
						<input type="hidden" name="edit" value="true"/>
						<input type="hidden" name="original" value="%s"/>
					<input type="submit" class="button" value="Save changes"/>
					<input type="button" class="button" value="Cancel" onclick="location.href='/domains';"/>
				</div>
			</div>
			<br/><br/><br/><br/><br /><br />
<br />

			</div>
			</form>
			]],domain,blocked,domain);
			printf("</td></tr>");
			
		else
			printf("<tr><th>Create a new domain</th></tr>");
			if (http.form.domain) then
				if (http.form.delete) then
					if (Mailman.deleteDomain(http.form.domain)) then
						printf("<tr><td><b><font color='red'>Deleted domain %s.</font></b></td></tr>", http.form.domain);
					else
						printf("<tr><td><b><font color='red'>Could not delete domain %s!</font></b></td></tr>", http.form.domain);
					end
				elseif (http.form.create) then
					Mailman.createDomain(http.form.domain, http.form.path or "");
					printf("<tr><td><b><font color='darkgreen'>Domain %s has been created.</font></b></td></tr>", http.form.domain);
				elseif (http.form.edit) then
					local flags = 0;
					if (http.form.block) then flags = 1; end
					Mailman.updateDomain(http.form.original, http.form.domain, http.form.path, flags);
					printf("<tr><td><b><font color='darkgreen'>Domain %s has been updated.</font></b></td></tr>", http.form.domain);
				end
			end
			
			printf("<tr><td>");
			printf([[
			<form action="/domains" method="post" id='create'>
			<div>
			<div >
				<div class='form_key'>
					Domain name:
				</div>
				<div class='form_value'>
					<input type="text" name="domain"/>
				</div>
			</div>
			
			<div>
				<div class='form_key'>
					Optional alt. storage path:
				</div>
				<div class='form_value'>
					<input type="text" name="path"/>
				</div>
			</div>
			
	
			<div class='form_el' id='domainsave' >
				<div class='form_key'>
						<input type="hidden" name="create" value="true"/>
					<input class="button" type="submit" value="Save domain"/>
					<input class="button"  type="reset" value="Reset"/>
				</div>
			</div>
			<br/><br/><br/><br/><br />
			</div>
			</form>
			]]);
			printf("</td></tr>");
		end
		printf("</table>");
	end
    
?>
</p>
<p>&nbsp;</p>
<table class="elements" border='0' cellpadding='5' cellspacing='1'>
  <tr><th>Domain</th><th>Actions</th></tr>
<?
    local t = Mailman.listDomains(); 
	local d = false;
    local domains = {};
	for k,v in pairs(t) do
		table.insert(domains, k);
	end
	table.sort(domains);
	for k,v in pairs(domains) do    
		d = true;
        if (session.credentials.admin or session.credentials.domains[v]) then
            printf("<tr><td><img src='/icons/house.png' align='absmiddle'/>&nbsp;<a href='/accounts:%s'><strong>%s</strong></a></td><td><a href=\"/domains:%s\"><img title='Edit domain' src='/icons/report_edit.png' align='absmiddle'/></a>  <a href=\"/domains?domain=%s&delete=true\"><img title='Delete domain' src='/icons/delete.png' align='absmiddle'/></a></td></tr>",v,v,v,v);
        end
    end
    if (not d) then
        printf("<tr><td colspan='3'><i>No domains are configured for this server yet.</i></td></tr>");
    end
?>
</table>