<link href="../rumblelua.css" rel="stylesheet" type="text/css" />
<div class="content">
<h2><img src="../icons/server.png" alt="server" width="128" height="136" hspace="5" align="left">Server info:</h2>
<p><strong>Operating environment: </strong>
  <?=session.info.os?> (<?=session.info.arch?> bit)<br>
  <strong>Server version:</strong>
<?=session.info.version?>
<br>
<strong>Uptime:</strong> 
<?
local hours = math.floor(session.info.uptime/3600);
local minutes = math.floor(math.fmod(session.info.uptime, 3600)/60);
local seconds = math.fmod(session.info.uptime, 60);
printf(string.format("%02u:%02u:%02u",  hours,minutes,seconds));
?>

</p>

<p>&nbsp;</p>

<table width="700" class="elements" border="0">
  <tr>
    <th width="109">Service</th>
    <th width="200">Status</th>
    <th width="147">Busy/Idle workers</th>
    <th width="112">Jobs handled</th>
    <th width="140">Traffic</th>
  </tr>
<?
	local total = 0;
    for k,v in pairs({"smtp", "imap4", "pop3", "mailman"}) do
        local svc = Rumble.serviceInfo(v);
		local status = (svc.enabled == 1 and "Running") or (svc.enabled == 0 and "Stopped") or "Paused";
		local icon = "<img src='/icons/service_" .. status:lower() .. ".png' align='absmiddle' />";
		local traffic = math.comma(svc.received + svc.sent);
		total = total + svc.received + svc.sent;
		printf("<tr><td><a href='/services:%s'>%s</a></td><td>%s %s</td><td align='right'>%u / %u</td><td align='right'>%u</td><td align='right'>%s bytes</td></tr>", v, v:upper(), icon, status, svc.busy, svc.idle, svc.sessions, traffic);
    end

	printf("<tr><td colspan='4' align='right'>Total:</td><td align='right'>%s bytes</td></tr>", math.comma(total) or "0");
?>



</table>
<p>&nbsp;</p>
<?
if (Rumble.readConfig("servername") == "mydomain.tld") then
	printf("<div class='notification'>Note: Your hostname (mydomain.tld) is <font color='#a30'>incorrect</font>.<br/>Please go to the <a href='/settings'>Server settings</a> page and correct this.</div>");
end
?>

</div>