<h2>Service information: <?=string.upper(session.section or "")?></h2>
<?
if ( session.section and session.credentials.admin ) then
	local svc = session.section;
	my.svcinfo = Rumble.serviceInfo(svc);
	local svctrl = nil;

	if (my.svcinfo) then
		if (http.form.pause) then
			Rumble.suspendService(session.section);
			svctrl = session.section:upper() .. " suspended!";
		elseif (http.form.start) then
			if (my.svcinfo.enabled == 2) then
				Rumble.resumeService(svc);
				svctrl = session.section:upper() .. " resumed!";
			elseif (my.svcinfo.enabled == 0) then
				Rumble.startService(svc);
				svctrl = session.section:upper() .. " started!";
			else
				svctrl = session.section:upper() .. " is already running!";
			end
		elseif (http.form.stop) then
			Rumble.stopService(svc);
			svctrl = session.section:upper() .. " stopped!";
		end
	else
		svctrl = "No such service: " .. svc:upper();	
	end
	if (svctrl) then
		printf("<div class='notification'>Service notification:<br/>" .. svctrl .. "</div>");
	end
end
?>

<h3>Traffic:</h3> <?
local sent, recv, total, jobs = math.comma(my.svcinfo.sent), math.comma(my.svcinfo.received),math.comma(my.svcinfo.sent + my.svcinfo.received), math.comma(my.svcinfo.sessions);
printf([[
<table border="0" cellspacing="5">
<tr><td><b>Jobs:</b></td><td align="right"> %s handled</td></tr>
<tr><td><b>Sent:</b></td><td align="right"> %s bytes</td></tr>
<tr><td><b>Received:</b></td><td align="right"> %s bytes</td></tr>
<tr ><td><b>Total:</b></td><td align="right"style="border-top: 1px solid #000; border-bottom: 1px solid #000;"> %s bytes</td></tr>
</table>
]], jobs, sent, recv, total);
?>