<h1>Server settings</h1>

<?
if (not session.credentials.admin) then
	printf("<div class='notification'>You need admin priveledges to access this page!</div>");
	stop();
end
if (session.section and http.form.save and session.credentials.admin) then
	printf("Saving " .. Rumble.readConfig("config-dir") .. "/rumble.conf");
	local f = io.open(Rumble.readConfig("config-dir") .. "/rumble.conf", "r");
    if (f) then
	    local cfg = f:read("*a");
	    f:close();
	    cfg = cfg:gsub("(\n%s*)(%w+)(%s+)([^\r\n]+)", 
			function(x,a,b,c)
				local k = a:lower();
				if (k == "servername") then c = http.form.servername;end
				if (k == "forceipv4") then c = http.form.forceipv4 or 0;end
				if (k == "storagefolder") then c = http.form.mailpath;end
				if (k == "datafolder") then c = http.form.dbpath;end
				if (k == "enablesmtp") then c = http.form.smtp or 0;end
				if (k == "enablepop3") then c = http.form.pop3 or 0;end
				if (k == "enableimap4") then c = http.form.imap4 or 0;end
				if (k == "smtpport") then c = http.form.smtpport or "";end
				if (k == "pop3port") then c = http.form.pop3port or "";end
				if (k == "imap4port") then c = http.form.imap4port or "";end				
				return x..a..b..c;
			end
		);
        local f = io.open(Rumble.readConfig("config-dir") .. "/rumble.conf", "w+");
        f:write(cfg);
        f:close();
    end
    Rumble.reloadConfiguration();
	session:send("HTTP/1.1 302 Moved\r\nLocation: /settings:save\r\n\r\n");
	exit();
end
if (session.section ~= "") then
	printf("<div class='notification'>Settings saved!</div>");
end

?>
<form id="form1" name="form1" method="post" action="/settings:save">
<input type="hidden" name="save" value="true"/>
  <table width="572" border="0" cellpadding="4">
    <tr>
      <td colspan="3"><h3>Global configuration</h3></td>
    </tr>
    <tr>
      <td width="179"><strong>Server name:</strong></td>
      <td colspan="2"><label for="servername"></label>
      <input type="text" name="servername" id="servername" value="<?=Rumble.readConfig("servername")?>" /> 
      (fx. mx.mydomain.com)</td>
    </tr>
    <tr>
      <td><strong>Force IPv4 networking:</strong></td>
      <td width="248"><input value="1" name="forceipv4" type="checkbox" id="forceipv4" 
      <?
      if (Rumble.readConfig("forceipv4") == "1") then printf("checked=\"checked\""); end
	  ?>/>
      <label for="forceipv4"></label></td>
      <td width="113">&nbsp;</td>
    </tr>
    <tr>
      <td height="23" colspan="3"><hr /></td>
    </tr>
    <tr>
      <td colspan="3"><h3><strong>Storage and folders</strong></h3></td>
    </tr>
    <tr>
      <td><strong>Mail storage folder:</strong></td>
      <td><label for="mailpath"></label>
      <input name="mailpath" type="text" id="mailpath" size="40" value="<?=Rumble.readConfig("storagefolder")?>" /></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><strong>Database folder:</strong></td>
      <td><label for="dbpath"></label>
      <input name="dbpath" type="text" id="dbpath" size="40" value="<?=Rumble.readConfig("datafolder")?>"  /></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><strong>Database engine:</strong></td>
      <td><input name="radio" type="radio" id="dbengine" value="dbengine" checked="checked" />
        <label for="dbengine"></label>
      sqlite3</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td height="23" colspan="3"><hr /></td>
    </tr>
    <tr>
      <td colspan="3"><h3><strong>Services</strong></h3></td>
    </tr>
    <tr>
      <td><strong>Enable SMTP server:</strong></td>
      <td><label>
        <input name="smtp" type="radio" id="smtp_0" value="0" 
        <?
      if (Rumble.readConfig("enablesmtp") == "0") then printf("checked=\"checked\""); end
	  ?>
        />
        No</label>
&nbsp;&nbsp;
<label>
  <input type="radio" name="smtp" value="1" id="smtp_1" 
        <?
      if (Rumble.readConfig("enablesmtp") == "1") then printf("checked=\"checked\""); end
	  ?>/>
  Yes, on port:</label>

<input name="smtpport"  value="<?=Rumble.readConfig("smtpport")?>" type="text" id="smtpport" size="3" maxlength="5" style="text-align:right;" /></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><strong>Enable POP3 server:</strong></td>
      <td><label>
        <input type="radio" name="pop3" value="0" id="smtp_2" 
        <?
      if (Rumble.readConfig("enablepop3") == "0") then printf("checked=\"checked\""); end
	  ?>/>
        No</label>
&nbsp;&nbsp;
<label>
  <input type="radio" name="pop3" value="1" id="smtp_3" 
        <?
      if (Rumble.readConfig("enablepop3") == "1") then printf("checked=\"checked\""); end
	  ?> />
  Yes, on port:</label>

<input name="pop3port"  value="<?=Rumble.readConfig("pop3port")?>" type="text" id="pop3port" size="3" maxlength="5" style="text-align:right;" /></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><strong>Enable IMAP4 server: </strong></td>
      <td><label>
        <input type="radio" name="imap4" value="0" id="smtp_4" 
        <?
      if (Rumble.readConfig("enableimap4") == "0") then printf("checked=\"checked\""); end
	  ?>/>
        No</label>
&nbsp;&nbsp;
<label>
  <input type="radio" name="imap4" value="1" id="smtp_5" 
        <?
      if (Rumble.readConfig("enableimap4") == "1") then printf("checked=\"checked\""); end
	  ?>/>
  Yes, on port:</label>

<input name="imap4port"  value="<?=Rumble.readConfig("imap4port")?>" type="text" id="imap4port" size="3" maxlength="5" style="text-align:right;" /></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td height="23" colspan="3"><hr /></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" name="Save settings" id="Save settings" value="Save settings" />&nbsp;&nbsp;&nbsp;        <input type="reset" name="Reset" id="button" value="Reset" /></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3"><div align="center"><em><br />
      Some settings may not take effect until the server has been restarted.</em></div></td>
    </tr>
  </table>
</form>
<p>&nbsp;</p>
<p>&nbsp;</p>
<?

if (session.section == "reload" and session.credentials.admin) then
	printf(Rumble.readConfig("config-dir") .. "/rumble.conf");
	local f = io.open(Rumble.readConfig("config-dir") .. "/rumble.conf", "r");
    if (f) then
	    local cfg = f:read("*a");
	    f:close();
	    cfg = cfg:gsub("mydomain.tld", "gruno.dk");
        local f = io.open(Rumble.readConfig("config-dir") .. "/rumble.conf", "w+");
        f:write(cfg);
        f:close();
    end
    Rumble.reloadConfiguration();
--	Rumble.reloadModules();
    printf("<b>Modules have been reloaded!</b>");
end
?>

</pre>

