<link href="../rumblelua.css" rel="stylesheet" type="text/css" />
<div class="content">
<h2><img src="../icons/server.png" alt="server" width="128" height="136" hspace="5" align="left">Server log:</h2>
<br/><br/><br/><br/><br/><br/>
<code>
<?
local colors = {
	core = 282,
	smtp = 228,
	pop3 = 228,
	imap4 = 228,
	startup = 882,
	db = 828,
	module = 852,
	mailman = 284
};

for i,entry in pairs(Rumble.getLog()) do
	local color = "993333";
	local date, svc, log = string.match(entry, "(%d+/%d+/%d+ %d+:%d+:%d+) %[([^%]]+)%]:%s+(.*)");
	for k,c in pairs(colors) do
		if (svc == k) then
			color = c;
			break;
		end
	end
	log = log:gsub("<", "&lt;");
	log = log:gsub("(%d[%d%.]+)", "<span style='color: #996622;'>%1</span>");
	
	printf("<div style='border: 1px dotted #522; margin: 3px; width: 700px;'>%s <b style='color: #%s;'>%-7s</b> %s</div>", date, color, svc, log);
end
?>
</code>
</p>



</div>

